[package]
name = "aoc09"
version = "0.1.0"
authors = ["Stefan Seering <s.seering@helferapp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = ""
num-traits = ""
